version: '2'

services:

  git-server:
    image: jkarlos/git-server-docker
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ~/git-server/keys:/git-server/keys
    - ~/git-server/repos:/git-server/repos
    environment:
      - PUID=1000
      - PGID=1000
      # Uncomment and adjust to match your host user's UID/GID to avoid permission issues
      # You can find your UID/GID with: id -u and id -g
      #- PUID=1001
      #- PGID=1001

